version: '3'
services:
  db:
    image: postgres
    env_file:
      - .envs/.db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .envs/.development
    depends_on:
      - db
  migrations:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    depends_on:
      - db
    restart: "on-failure"