# Generated by Django 4.1.5 on 2023-01-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requested',
            field=models.IntegerField(default=0),
        ),
    ]
